# Default values for sampleapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: amagdi888/nodeapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.16.1

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 3000
  nodeport: 30000
